matching_groups:
  - /user/[^/]+/gacha/index
  - /user/[^/]+/gacha/draw/[^/]+/[^/]+
  - /user/[^/]+/present/index/[^/]+
  - /user/[^/]+/present/receive
  - /user/[^/]+/item
  - /user/[^/]+/card/addexp/[^/]+
  - /user/[^/]+/card
  - /user/[^/]+/reward
  - /user/[^/]+/home
  - /admin/user/[^/]+/ban
  - /admin/user/[^/]+
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.ndjson
